---
title:               jefflamth
tagline:             Jeff Lam Tian Hung is a Geekstah.
login:               <%= ENV["obtvse_login"] ? ENV["obtvse_login"] : "jefflamth@gmail.com" %>
password:            <%= ENV["obtvse_password"] ? ENV["obtvse_password"] : "jefflam" %>
name:                Jeff Lam Tian Hung
twitter:             jefflamth
github:              jefflam
email:               jefflamth@gmail.com
google_analytics_id: YOUR_GA_ID